taskmanager/urls.py
from rest_framework.routers import DefaultRouter
from .views import TodolistViewSet

# router = DefaultRouter(trailing_slash=False)
router = DefaultRouter()

app_name = "taskmanagerapp"


router.register(
    prefix="tasks",
    viewset=TodolistViewSet,
    basename="tasks",
)

urlpatterns = router.urls

todo/urls.py
from django.contrib import admin
from django.urls import path, include
from taskmanager.views import current_datetime, redirect_view
from taskmanager.views import *
# (
#     MyModelListView,
#     MyModelUpdateView,
#     MyModelCreateView,
#     MyModelDeleteView,
#     MyModelDetailView,
#     SprintListView,
#     SprintUpdateView,
#     SprintCreateView,

#     )
from rest_framework.schemas import get_schema_view

urlpatterns = [
    path('', redirect_view ),
    path("admin/", admin.site.urls),
    path("time/", current_datetime),
    path("tasklist/", MyModelListView.as_view()),
    path("taskupdate/<int:pk>", MyModelUpdateView.as_view()),
    path("taskcreate/", MyModelCreateView.as_view()),
    path("taskdelete/<int:pk>", MyModelDeleteView.as_view()),
    path("taskdetail/<int:pk>", MyModelDetailView.as_view()),
    path("sprintlist/", SprintListView.as_view()),
    path("sprintupdate/<int:pk>", SprintUpdateView.as_view()),
    path("sprintcreate/", SprintCreateView.as_view()),
    path("sprintdelete/<int:pk>", SprintDeleteView.as_view()),
    path("sprintdetail/<int:pk>", SprintDetailView.as_view()),
    path("projectlist/", ProjectListView.as_view()),
    path("projectupdate/<int:pk>", ProjectUpdateView.as_view()),
    path("projectcreate/", ProjectCreateView.as_view()),
    path("projectdelete/<int:pk>", ProjectDeleteView.as_view()),
    path("projectdetail/<int:pk>", ProjectDetailView.as_view()),
    path("api/", include("taskmanager.urls")),

    path('openapi/', get_schema_view(
        title="Studying",
        description="API for all things …",
        version="1.0.0"
    ), name='openapi-schema'),
]

taskmanager/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
import logging
# from django.contrib.auth.models import Group, User
from django_extensions.db import models as ext_models

logger = logging.getLogger(__name__)

class TaskStatus(models.Model):

    status = models.CharField(max_length=150, help_text="Статус задачи")

    def __str__(self) -> str:
        return f'{self.status}'

    class Meta:
        verbose_name_plural = 'Task statuses'

class Project(ext_models.TimeStampedModel):
    
    name = models.CharField(max_length=250, help_text="Описание проекта")
    # is_active = models.BooleanField(default=True, help_text="Отметка о состоянии проекта")
    # dead_line = models.DateField(
    #     default=None,
    #     null=True,
    #     help_text="Дата, до которой должен быть выполнен проект"
    # )
    complete_time = models.DateTimeField(
        default=None,
        auto_now=False,
        blank=True,
        null=True,
        help_text="Время завершения проекта"
    )

    def save(self, *args, **kwargs) -> None:
        logger.warning(f'Save project "{self.name}"')
        # if self.is_active and self.complete_time:
        #     self.complete_time = None
        # elif not self.is_active and self.complete_time is None:
        #     self.complete_time = timezone.now()
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'Project: {self.name}'
    
    class Meta:
        ordering = ["created"]

class Sprint(ext_models.TimeStampedModel):
    
    name = models.CharField(max_length=250, help_text="Описание спринта")
    is_active = models.BooleanField(default=True, help_text="Отметка о состоянии спринта")
    dead_line = models.DateField(
        default=None,
        null=True,
        help_text="Дата, до которой должен быть выполнен спринт"
    )
    complete_time = models.DateTimeField(
        default=None,
        auto_now=False,
        blank=True,
        null=True,
        help_text="Время завершения спринта"
    )
    project = models.ForeignKey(
        to=Project,
        on_delete=models.CASCADE,
        null=True,
        related_name='project_sprints',
        help_text='Ссылки на id проекта для спринта'
    )

    def save(self, *args, **kwargs) -> None:
        logger.warning(f'Save sprint "{self.name}"')
        if self.is_active and self.complete_time:
            self.complete_time = None
        elif not self.is_active and self.complete_time is None:
            self.complete_time = timezone.now()
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'Sprint: {self.name} | deadline {self.dead_line.strftime("%d.%m.%Y")}'
    
    class Meta:
        ordering = ["created"]

class Task(ext_models.TimeStampedModel):
    
    name = models.CharField(max_length=250, help_text="Описание задачи")
    # is_active = models.BooleanField(default=True, help_text="Отметка о состоянии задачи")
    dead_line = models.DateField(
        default=None,
        null=True,
        help_text="Дата, до которой должна быть выполнена задача"
    )
    complete_time = models.DateTimeField(
        default=None,
        auto_now=False,
        blank=True,
        null=True,
        help_text="Время завершения задачи"
    )
    status = models.ForeignKey(
        to=TaskStatus,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='status_tasks',
        help_text='Статус',
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='user_tasks',
        help_text='Исполнитель',
    )
    parent_task = models.ForeignKey(
        to='self',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='sub_task',
        help_text='Родительская задача'
    )
    sprint = models.ForeignKey(
        to=Sprint,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='sprint_tasks',
        help_text='Связь со спринтами'
    )

    def save(self, *args, **kwargs) -> None:
        logger.warning(f'Save task "{self.name}"')
        logger.warning(f'Save task in sprint "{self.sprint}"')
        # if self.is_active and self.complete_time:
        #     self.complete_time = None
        # elif not self.is_active and self.complete_time is None:
        #     self.complete_time = timezone.now()#.strftime("%d.%m.%Y")
        return super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.name} | deadline {self.dead_line.strftime("%d.%m.%Y")}'
    
    class Meta:
        ordering = ["created"]

taskmanager/forms.py
from django import forms
from taskmanager.models import Task

class ParentTaskSelect(forms.Select):
    def create_option(self, name, value, label, selected, index, subindex=None, attrs={'class': 'form-select'}):
        option = super().create_option(name, value, label, selected, index, subindex, attrs)
        if value:
            option['attrs']['name'] = value.instance.name
        return option

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            # 'is_active',
            'dead_line',
            'parent_task'
        ]
        widgets = {'parent_task': ParentTaskSelect}


class CreateForm(forms.ModelForm):

    email = forms.EmailField()
    reason = forms.ChoiceField(
        choices=[("COMMENT", "Comment"), ("COMMENT", "Complaint")],
        widget=forms.Select,
        required=False,
    )
    comment = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Task
        fields = [
            'name',
            # 'is_active',
            'dead_line',
            'parent_task'
        ]
        widgets = {
            'dead_line': forms.DateInput(),
            'parent_task': forms.Select(attrs={'class': "form-select"})
        }


class FeedbackModelForm(forms.ModelForm):
    
    class Meta:
        model = Feedback
        fields = ["email", "reason", "comment"]
        widgets = {
            'comment' : forms.Textarea(attrs={'cols': 100, "rows": 40})
        }

taskmanager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.utils import timezone
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from taskmanager.models import Task, TaskStatus, Sprint, Project
from .serializers import TodoSerializer
from .filters import TodoFilterSet
from django.template import loader
from django.contrib.auth import get_user_model

# from datetime import datetime

from rest_framework import viewsets, mixins
from rest_framework import permissions
from rest_framework.schemas.openapi import AutoSchema

User = get_user_model()

def current_datetime(request):
    now = timezone.now()
    # now = datetime.now()
    # html = f'<html><body><h2>{now}</h2><br>{request.user}</body></html>'
    template_name = 'time.html'
    # return HttpResponse(html)
    return render(request, template_name, {'now': now, 'user': request.user})

def redirect_view(request):
	return redirect("/tasklist")

# class UserlistViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
#     queryset = User.objects.all().order_by('-username')
#     serializer_class = UserSerializer
#     # filterset_class =  TodoFilterSet

#     def list(self, request, *args, **kwargs):
#         '''.'''
#         return super().list(request, *args, **kwargs)
    
# class StatuslistViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
#     queryset = TaskStatus.objects.all().order_by('-status')
#     serializer_class = StatusSerializer

class TodolistViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all().order_by('-id')
    serializer_class = TodoSerializer
    filterset_class =  TodoFilterSet

    schema = AutoSchema(
        tags=['Tasks'],
        component_name='Task',
        operation_id_base='Task',
    )

class MyModelListView(ListView):
    model = Task
    template_name = 'todo_list.html'

class MyModelUpdateView(UpdateView):
    model = Task
    fields = [
        'name',
        # 'is_active',
        'dead_line',
        'parent_task',
        'user',
        'status',
        'sprint'
    ]
    object_list = Task.objects.all().order_by('id')
    template_name = 'todo_update_form.html'
    success_url = '/tasklist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = TaskStatus.objects.all()
        context['users'] = User.objects.all()
        context['sprints'] = Sprint.objects.all().order_by('name')
        return context

class MyModelCreateView(CreateView):
    model = Task
    fields = [
        'name',
        # 'is_active',
        'dead_line',
        'parent_task',
        'user',
        'status'
    ]
    template_name = 'todo_create_form.html'
    success_url = '/tasklist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = TaskStatus.objects.all()
        context['users'] = User.objects.all()
        return context

class MyModelDeleteView(DeleteView):
    model = Task
    template_name = 'todo_delete_form.html'
    success_url = '/tasklist/'

class MyModelDetailView(DetailView):
    model = Task
    template_name = 'todo_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    
class SprintListView(ListView):
    model = Sprint
    template_name = 'sprint_list.html'

class SprintUpdateView(UpdateView):
    model = Sprint
    fields = [
        'name',
        'is_active',
        'dead_line',
        'project'
    ]
    object_list = Sprint.objects.all().order_by('created')
    template_name = 'sprint_update_form.html'
    success_url = '/sprintlist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all().order_by('name')
        return context

class SprintCreateView(CreateView):
    model = Sprint
    fields = [
        'name',
        # 'is_active',
        'dead_line',
    ]
    template_name = 'sprint_create_form.html'
    success_url = '/sprintlist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        return context

class SprintDeleteView(DeleteView):
    model = Sprint
    template_name = 'sprint_delete_form.html'
    success_url = '/sprintlist/'

class SprintDetailView(DetailView):
    model = Sprint
    template_name = 'sprint_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # try:
        #     context['sprint_tasks'] = Sprint.objects.filter(name='1')[0].sprint_tasks.all()
        # except:
        #     pass
        return context
    
class ProjectListView(ListView):
    model = Project
    template_name = 'project_list.html'

class ProjectUpdateView(UpdateView):
    model = Project
    fields = [
        'name',
    ]
    object_list = Project.objects.all().order_by('created')
    template_name = 'project_update.html'
    success_url = '/projectlist/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sprint'] = Task.objects.all().order_by('name')
        return context

class ProjectCreateView(CreateView):
    model = Project
    fields = [
        'name',
    ]
    template_name = 'project_create.html'
    success_url = '/projectlist/'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['projects'] = Project.objects.all()
    #     return context

class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'project_delete.html'
    success_url = '/projectlist/'

class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

taskmanager/templates/project_create.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Create project</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}

        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ form.name.id_for_label }}">Project text</label>
            <textarea class="form-control" name="name" id="id_name" placeholder="Project text" rows="5"></textarea>
        </div>
        <!-- <div class="form-check form-switch pt-1">
            <input class="form-check-input" type="checkbox" name="is_active" id="id_is_active" checked>
            <label class="form-lable" for="{{ form.is_active.id_for_label }}">Task in progress</label>
        </div> -->
        <!-- <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ form.dead_line.id_for_label }}">Deadline</label>
            <input type="date" value="now" name="dead_line" id="id_dead_line">
        </div> -->
        <!-- <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.project.id_for_label }}">Project</label>
            <select class="form-select" id="id_project" name="project">
                <option selected value="">--------</option>
                {% for project_ in projects %}
                    <option value="{{ project_.id }}">{{ project_.name }}</option>
                {% endfor %}
            </select>
        </div> -->
        <div class="btn-group py-5" role="group">
            <input class="btn btn-secondary" type="submit" value="Save">
            <input class="btn btn-dark" type="reset" value="Reset"></input>
            <a class="btn btn-secondary" href="../projectlist/">Cancel</a>
        </div>
    </form>
    <!-- <script>
        document.getElementById('id_dead_line').valueAsDate = new Date();
    </script> -->
</div>
{% endblock %}

taskmanager/templates/sprint_create_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Create sprint</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}

        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ form.name.id_for_label }}">Sprint text</label>
            <textarea class="form-control" name="name" id="id_name" placeholder="Task text" rows="5"></textarea>
        </div>
        <!-- <div class="form-check form-switch pt-1">
            <input class="form-check-input" type="checkbox" name="is_active" id="id_is_active" checked>
            <label class="form-lable" for="{{ form.is_active.id_for_label }}">Task in progress</label>
        </div> -->
        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ form.dead_line.id_for_label }}">Deadline</label>
            <input type="date" value="now" name="dead_line" id="id_dead_line">
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.project.id_for_label }}">Project</label>
            <select class="form-select" id="id_project" name="project">
                <option selected value="">--------</option>
                {% for project_ in projects %}
                    <option value="{{ project_.id }}">{{ project_.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="btn-group py-5" role="group">
            <input class="btn btn-secondary" type="submit" value="Save">
            <input class="btn btn-dark" type="reset" value="Reset"></input>
            <a class="btn btn-secondary" href="../tasklist/">Cancel</a>
        </div>
    </form>
    <script>
        document.getElementById('id_dead_line').valueAsDate = new Date();
    </script>
</div>
{% endblock %}

taskmanager/templates/sprint_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Sprint detail view</h5>
</div>
<div class="container pt-2">
    <div class="mb-3 pt-1">
        <label class="form-label" for="{{ object.name.id_for_label }}">Sprint text</label>
        <textarea class="form-control" name="name" id="id_name" rows="5" readonly>{{ object.name }}</textarea>
    </div>
    <div class="mb-3 pt-1">
        <label class="form-lable" for="{{ object.dead_line.id_for_label }}">Deadline</label>
        <input type="date" value='{{ object.dead_line|date:"Y-m-d" }}' name="dead_line" id="id_dead_line" readonly>
    </div>
    <div class="form-check form-switch pt-1">
        <input class="form-check-input" type="checkbox" role="switch" name="is_active" id="id_is_active"
        {% if object.is_active %}
        checked
        {% endif %} disabled/>
        <label class="form-lable" for="{{ object.is_active.id_for_label }}">Sprint in progress</label>
    </div>
    <div class="mb-3 pt-1">
        <label class="form-lable" for="{{ object.created.id_for_label }}">Sprint creted time</label>
        <input type="datetime" value='{{ object.created|date:"d.m.Y H:i" }}' name="created" id="id_created" readonly>
    </div>
    {% if object.complete_time %}
        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ object.complete_time.id_for_label }}">Finished at</label>
            <input type="datetime" value='{{ object.complete_time|date:"Y-m-d H:i" }}' name="complete_time" id="id_complete_time" readonly>
        </div>
    {% endif %}
        <label class="form-label">Sprint tasks</label>
        <ol class="list-group">
        {% for item_ in object.sprint_tasks.all %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ item_.name }}</div>
                    Deadline: {{ item_.dead_line|date:"d.m.Y" }}
                </div>
                <!-- <span class="badge bg-primary rounded-pill">14</span> -->
            </li>
        {% empty %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                    <div class="fw-bold">No tasks in sprint yet</div>
                </div>
                <!-- <span class="badge bg-primary rounded-pill">14</span> -->
            </li>
        {% endfor %}
        </ol>
    
        <div class="btn-group py-5" role="group">
            <a class="btn btn-warning" href="../sprintdelete/{{ object.id }}">Del</a>
            <a class="btn btn-primary" href="../sprintupdate/{{ object.id }}">Edit</a>
            <a class="btn btn-secondary" href="../sprintlist/">Cancel</a>
        </div>
    </div>
</div>
{% endblock %}

taskmanager/templates/todo_create_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Create task</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}

        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ form.name.id_for_label }}">Task text</label>
            <textarea class="form-control" name="name" id="id_name" placeholder="Task text" rows="5"></textarea>
        </div>
        <div class="form-check form-switch pt-1">
            <input class="form-check-input" type="checkbox" name="is_active" id="id_is_active" checked>
            <label class="form-lable" for="{{ form.is_active.id_for_label }}">Task in progress</label>
        </div>
        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ form.dead_line.id_for_label }}">Deadline</label>
            <input type="date" value="now" name="dead_line" id="id_dead_line">
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.parent_task.id_for_label }}">Parent task</label>
            <select class="form-select" id="id_parent_task" name="parent_task">
                <option selected value="">No parent task</option>
            </select>
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.user.id_for_label }}">Executor</label>
            <select class="form-select" id="id_user" name="user">
                <option selected value="">No user</option>
                {% for user_ in users %}
                    <option value="{{ user_.id }}">{{ user_.username }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-2 pt-2">
            <label class="form-lable" for="{{ form.status.id_for_label }}">Status</label>
            <select class="form-select" id="id_status" name="status">
                <option selected value="">--------</option>
                {% for status_ in statuses %}
                    <option value="{{ status_.id }}">{{ status_.status }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="btn-group py-5" role="group">
            <input class="btn btn-secondary" type="submit" value="Save">
            <input class="btn btn-dark" type="reset" value="Reset"></input>
            <a class="btn btn-secondary" href="../tasklist/">Cancel</a>
        </div>
    </form>
    <script>
        document.getElementById('id_dead_line').valueAsDate = new Date();
    </script>
</div>
{% endblock %}

taskmanager/templates/todo_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Task detail view</h5>
</div>
<div class="container pt-2">
    <div class="mb-3 pt-1">
        <label class="form-label" for="{{ object.name.id_for_label }}">Task text</label>
        <textarea class="form-control" name="name" id="id_name" rows="5" readonly>{{ object.name }}</textarea>
    </div>
    <div class="mb-3 pt-1">
        <label class="form-lable" for="{{ object.dead_line.id_for_label }}">Deadline</label>
        <input type="date" value='{{ object.dead_line|date:"Y-m-d" }}' name="dead_line" id="id_dead_line" readonly>
    </div>
    <!-- <div class="form-check form-switch pt-1">
        <input class="form-check-input" type="checkbox" role="switch" name="is_active" id="id_is_active"
        {% if object.is_active %}
        checked
        {% endif %} disabled/>
        <label class="form-lable" for="{{ object.is_active.id_for_label }}">Task in progress</label>
    </div> -->
    <div class="mb-3 pt-1">
        <label class="form-lable" for="{{ object.created.id_for_label }}">Task creted time</label>
        <input type="datetime" value='{{ object.created|date:"d.m.Y H:i" }}' name="created" id="id_created" readonly>
    </div>
    {% if object.complete_time %}
        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ object.complete_time.id_for_label }}">Finished at</label>
            <input type="datetime" value='{{ object.complete_time|date:"Y-m-d H:i" }}' name="complete_time" id="id_complete_time" readonly>
        </div>
    {% endif %}
    {% if object.parent_task %}
        <div class="mb-3 pt-1">
            <label class="form-lable" for="{{ object.parent_task.id_parent_task }}">Parent task</label>
            <!-- <input type="input" value='{{ object.parent_task.name }}' name="parent_task" id="id_parent_task" readonly> -->
            <p>{{ object.parent_task.name }}</p>
        </div>
    {% endif %}
    <div class="mb-3 pt-1">
        <label class="form-lable" for="{{ object.user.id_user }}">Executor</label>
        <!-- <input type="input" value='{{ object.parent_task.name }}' name="parent_task" id="id_parent_task" readonly> -->
        <p>{{ object.user.username }}</p>
    </div>
    <div class="mb-3 pt-1">
        <label class="form-lable" for="{{ object.status.id_user }}">Status</label>
        <!-- <input type="input" value='{{ object.parent_task.name }}' name="parent_task" id="id_parent_task" readonly> -->
        <p>{{ object.status.status }}</p>
    </div>
        <!-- <p>Now {{ now|date:"d.m.Y" }}</p> -->
        <div class="btn-group py-5" role="group">
            <a class="btn btn-warning" href="../taskdelete/{{ object.id }}">Del</a>
            <a class="btn btn-primary" href="../taskupdate/{{ object.id }}">Edit</a>
            <a class="btn btn-secondary" href="../tasklist/">Cancel</a>
        </div>
    </div>
</div>
{% endblock %}

taskmanager/templates/todo_update_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container pt-2">
    <h5>Task update</h5>
</div>
<div class="container pt-2">
    <form method="post">{% csrf_token %}
        <!-- {{ form.as_p }} -->
        <div class="mb-3">
            <!-- {{ form.non_field_errors }} -->
            <div class="mb-3 pt-1">
                <label class="form-label" for="{{ object.name.id_for_label }}">Task text</label>
                <textarea class="form-control" name="name" id="id_name" rows="5">{{ form.name.value }}</textarea>
            </div>
            <div class="mb-3 pt-1">
                <label class="form-lable" for="{{ object.dead_line.id_for_label }}">Deadline</label>
                <input type="date" value='{{ object.dead_line|date:"Y-m-d" }}' name="dead_line" id="id_dead_line">
            </div>
            <div class="mb-2 pt-2">
                <label class="form-lable" for="{{ object.parent_task.id_for_label }}">Parent task</label>
                <select class="form-select" id="id_parent_task" name="parent_task">
                    {% if object.parent_task %}
                        <option selected value="{{ object.parent_task.id }}">{{ object.parent_task.name }}</option>
                        <option value="">No parent task</option>
                    {% else %}
                        <option selected value="">No parent task</option>
                    {% endif %}
                </select>
            </div>
            <div class="mb-2 pt-2">
                <label class="form-lable" for="{{ object.user.id_user }}">Executor</label>
                <select class="form-select" id="id_user" name="user">
                    {% if object.user %}
                        <option selected value="{{ object.user.id }}">{{ object.user.username }}</option>
                        <option value="">No task executor</option>
                    {% else %}
                        <option selected value="">No task executor</option>
                    {% endif %}
                    {% for user_ in users %}
                        <option value="{{ user_.id }}">{{ user_.username }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-2 pt-2">
                <label class="form-lable" for="{{ object.status.id_for_label }}">Status</label>
                <select class="form-select" id="id_status" name="status">
                    {% if object.status %}
                        <option selected value="{{ object.status.id }}">{{ object.status.status }}</option>
                        <option value="">--------</option>
                    {% else %}
                        <option selected value="">--------</option>
                    {% endif %}
                    {% for item_ in statuses %}
                        <option value="{{ item_.id }}">{{ item_.status }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-2 pt-2">
                <label class="form-lable" for="{{ object.sprint.id_for_label }}">Sprint</label>
                <select class="form-select" id="id_sprint" name="sprint">
                    {% if object.sprint %}
                        <option selected value="{{ object.sprint.id }}">{{ object.sprint.name }}</option>
                        <option value="">--------</option>
                    {% else %}
                        <option value="">--------</option>
                    {% endif %}
                    {% for item_ in sprints %}
                        <option value="{{ item_.id }}">{{ item_.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="btn-group py-5" role="group">
                <input class="btn btn-secondary" type="submit" value="Update"></input>
                <input class="btn btn-dark" type="reset" value="Reset"></input>
                <a class="btn btn-secondary" href="../tasklist/">Cancel</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}